feat: add LogicalInterface model
criteo/netbox-network-cmdb pull request #23
Opened 2023-09-05 08:46 UTC by djothi

**Description:**

Add LogicalInterface model.

2023-09-19 08:13 UTC, kpetremann commented on netbox_cmdb/netbox_cmdb/models/interface.py
> +    untagged_vlan = models.ForeignKey(
it is missing a constraint as untagged is only "access" ports and tagged/native are only for "trunk" ports.

authorized settings only:
- untagged
- tagged
- tagged + native

forbidden settings:
- untagged + tagged
- untagged + native
- untagged + tagged + native

2023-09-21 08:43 UTC, fdomain requested changes

2023-09-21 08:43 UTC, fdomain commented on netbox_cmdb/netbox_cmdb/models/interface.py
> +        blank=True,
In which cases do we allow to have an empty parent_interface? Loopback interfaces ?

2023-09-21 08:43 UTC, fdomain commented on netbox_cmdb/netbox_cmdb/models/interface.py
> +        blank=True,
as there is no name field for the logical interface, it seems to be mandatory to have a parent_interface

2024-01-03 16:34 UTC, djothi commented on netbox_cmdb/netbox_cmdb/models/interface.py
> +    monitoring_state = models.CharField(
IIRC we briefly talked about it, but nothing more. Let's schedule a dedicated meeting. The solution could also impact `BGPSession` monitoring fields

2024-01-04 09:45 UTC, kpetremann commented on netbox_cmdb/netbox_cmdb/models/interface.py
> +    monitoring_state = models.CharField(
it has already been discussed indeed, there was a page and a consensus :)
I'll share the page in slack

2024-01-04 10:51 UTC, kpetremann approved these changes

2024-01-04 12:21 UTC, fdomain approved these changes

2024-01-04 12:47 UTC, merged